apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-manager
spec:
  selector:
    matchLabels:
      app: employee-manager
  replicas: {{ .Values.replicasNumber }}
  template: # template for the pods
    metadata:
      labels:
        app: employee-manager
    spec:
      containers:
      - name: employee-manager
        image: localhost:32000/employee-manager: {{ .Values.containerImageTag }}
