pipeline {
    agent any

    stages {

        stage('MAVEN BUILD') {
            steps {
                echo 'Bulding MAVEN project...'
                sh 'mvn clean package -f employee-manager-h2db/pom.xml'  
                
            }
        }
        
        stage('DOCKER BUILD') {
            steps {
                echo 'Bulding DOCKER image...'
                sh 'docker build -t localhost:32000/employee-manager:${imageTag} employee-manager-h2db'  
                
            }
        }
        
        stage('DOCKER PUSH') {
            steps {
                echo 'Pushing DOCKER image...'
                sh 'docker push localhost:32000/employee-manager:${imageTag}'  
                
            }
        }
        
        stage('HELM') {
            steps {
                echo 'Helm upgrade command'
                sh 'helm install employee-manager employee-manager/ || helm upgrade --set containerImageTag=${imageTag} employee-manager employee-manager/'
                //sh 'helm upgrade --set containerImage=${imageName} employee-manager employee-manager/'
                    
            }
        }


    }
}
